### PR TITLE
fix(gr-sheet): Fix parsing of datum type

### LINKED ISSUE #13: Correcting the spreadsheet-to-json converter to use the Ellipsoid and Prime Meridian attributes for the Geodetic Datum sub-class
Reported by @maccraymer

## Summary

An error was encountered for both the `ISOGRv7a_ETRF2020_20241022_final.xlsx` and `ISOGRv7a_ETRF2020_20241022_final.xlsx`:

Datum(CD#)/CD1: error processing register item: Error: Ellipsoid and prime meridian are not recognized as properties of a Geodetic Datum

## Expected results

The converter should recognize that an ellipsoid and prime meridian are required attributes of a geodetic datum.

NOTE: They are not required for a vertical datum which is why the `CGVD28(HTv2)` spreadsheet was converted without any problems.

### PR DESCRIPTION
**Pull request by ribose-jeffreylau**
Fixes #13

### CODE REVIEW

File: packages/gr-sheet/src/index.ts [hunk 1]
```diff
@@ -717,7 +717,7 @@ const SupportedSheets = {
         extentRef,
         coordinateReferenceEpoch: item.coordinateReferenceEpoch.trim() || null,
       } as const;
-      if (item.type === 'GeodeticDatum') {
+      if (/geodetic(?: *datum *)?$/i.test(item.type)) {
```
Comment (strogonoff) [inline packages/gr-sheet/src/index.ts:720]: I mean, if it works it works. To be honest this application of regexes triggers me, I suppose it could be simpler, but I won’t request this to be changed (not to mess with black magic that regexes are)

**Review by strogonoff — APPROVED** [review]
If it’s tested, it LGTM.
