### PR TITLE
fix(gr-sheet): Add support for Integer

### LINKED ISSUE #12: Updating the spreadsheet-to-json converter to use the new unitless parameter type “Integer”
Reported by @maccraymer

## Summary

> the spreadsheet has been updated to include the new Integer parameter type (attached). I have also attached an example using the new type. Note that the spreadsheet improperly shows the Integer parameter types as failing the spreadsheet integrity check. That will be fixed.

### PR DESCRIPTION
**Pull request by ribose-jeffreylau**
Fixes #12

### CODE REVIEW

**Comment by ribose-jeffreylau** [comment]
As a record, here is the log from before this change, using `ISOGRv8_NAD83v8Transf_20241215_import.xslx`:

```
Using convertor gr-sheet
Reading uploaded data…
Prepare proposal: Generated proposal 5ae1fcde-5dda-46e8-b6dd-5ff80566d524
Caching items
Source_Citation(CI#)/CI1: not outputting a register item
Handling GR item CT1
Coord_Trans(CT#)/CT1: error processing register item: Error: Identifier ‘’ is unparseable or invalid
Handling GR item CT2
Coord_Trans(CT#)/CT2: error processing register item: Error: Identifier ‘’ is unparseable or invalid
Handling GR item CT3
Coord_Trans(CT#)/CT3: error processing register item: Error: Identifier ‘’ is unparseable or invalid
Handling GR item CT4
Coord_Trans(CT#)/CT4: error processing register item: Error: Identifier ‘’ is unparseable or invalid
Handling GR item CT5
Coord_Trans(CT#)/CT5: error processing register item: Error: Identifier ‘’ is unparseable or invalid
Handling GR item CT6
Coord_Trans(CT#)/CT6: error processing register item: Error: Identifier ‘’ is unparseable or invalid
Handling GR item CT7
Coord_Trans(CT#)/CT7: error processing register item: Error: Identifier ‘’ is unparseable or invalid
Handling GR item CT8
Coord_Trans(CT#)/CT8: error processing register item: Error: Identifier ‘’ is unparseable or invalid
Handling GR item CT9
Coord_Trans(CT#)/CT9: error processing register item: Error: Identifier ‘’ is unparseable or invalid
Handling GR item CT10
Coord_Trans(CT#)/CT10: error processing register item: Error: Identifier ‘’ is unparseable or invalid
Handling GR item CT11
Coord_Trans(CT#)/CT11: error processing register item: Error: Identifier ‘’ is unparseable or invalid
ParamVal(PV#)/PV1: not outputting a register item
ParamVal(PV#)/PV2: not outputting a register item
ParamVal(PV#)/PV3: not outputting a register item
ParamVal(PV#)/PV4: not outputting a register item
ParamVal(PV#)/PV5: not outputting a register item
ParamVal(PV#)/PV6: not outputting a register item
ParamVal(PV#)/PV7: not outputting a register item
ParamVal(PV#)/PV8: not outputting a register item
ParamVal(PV#)/PV9: not outputting a register item
ParamVal(PV#)/PV10: not outputting a register item
ParamVal(PV#)/PV11: not outputting a register item
ParamVal(PV#)/PV12: not outputting a register item
ParamVal(PV#)/PV13: not outputting a register item
ParamVal(PV#)/PV14: not outputting a register item
ParamVal(PV#)/PV15: not outputting a register item
ParamVal(PV#)/PV16: not outputting a register item
ParamVal(PV#)/PV17: not outputting a register item
ParamVal(PV#)/PV18: not outputting a register item
ParamVal(PV#)/PV19: not outputting a register item
ParamVal(PV#)/PV20: not outputting a register item
ParamVal(PV#)/PV21: not outputting a register item
ParamVal(PV#)/PV22: not outputting a register item
1 results obtained.
```

**Comment by ribose-jeffreylau** [comment]
Integer values now show up in Paneron.

File: packages/gr-sheet/src/index.ts [hunk 1]
```diff
@@ -26,6 +26,7 @@ import { teeAsync } from '../../common/src/util.js';
 export const ParameterType = {
   FILE: 'parameter file name',
   MEASURE: 'measure (w/ UoM)',
+  INTEGER: 'integer value',
```
Comment (strogonoff) [inline packages/gr-sheet/src/index.ts:29]: @ribose-jeffreylau take a look at this: https://github.com/paneron/extension-geodetic-registry/blob/1366ad19d6cacf4ae571cf01241a12bf7ad6ca4d/src/classes/transformation.tsx#L36

The actual value of the constant looks right, but could you perhaps rename the constant to match `INTEGER_VALUE` for consistency?

**Review by strogonoff — CHANGES_REQUESTED** [review]
@ribose-jeffreylau if you have tested and it works, then it looks good to me, except with maybe the renaming of the constant for consistency… Though it’s not too big of a deal.

File: packages/gr-sheet/src/index.ts (hunk 1 above)
Comment (strogonoff) [reply packages/gr-sheet/src/index.ts:29]: It is unfortunate that we cannot import it properly, it may be related to the same packaging issue that causes the TSC errors you encountered earlier.

Comment (ribose-jeffreylau) [reply packages/gr-sheet/src/index.ts:29]: I can do that.
